name: Build and push docker images

on:
  push:
    branches: main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup docker build
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push App Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: amdocker32695/springbootdemo-app:latest

      - name: Build and Push DB Image
        if: false
        uses: docker/build-push-action@v5
        with:
          context: ./db
          push: true
          tags: amdocker32695/custom-postgres:latest
